project:
  type: website

website:
  title: "climate_change"
  navbar:
    right:
      - href: index.qmd
        text: Home      
      - href: about.qmd
        text: Analysis
    #- icon: github
    #  href: https://github.com/NASA-Openscapes
    search: true
    
format:
  html:
    theme: [sandstone, custom.scss]
    css: styles.css
    toc: true
    toc-title: Contents
    toc-location: left
    link-external-newwindow: true
    date-format: "MMM YYYY"
    smooth-scroll: true

